[colors.bright]
black = "0x5c5855"
blue = "0x01a0e4"
cyan = "0xb5e4f4"
green = "0xa84b52"
magenta = "0xa22e35"
red = "0xdb2d20"
white = "0xf7f7f7"
yellow = "0xfded02"

[colors.normal]
black = "0x090300"
blue = "0x01a0e4"
cyan = "0xb5e4f4"
green = "0xa84b52"
magenta = "0xa22e35"
red = "0xdb2d20"
white = "0xa5a2a2"
yellow = "0xfded02"

[colors.primary]
background = "0x12120e"
foreground = "0xa2afaf"

[font]
size = 12.0

[font.bold]
family = "MonaspiceNe NF"
style = "Bold"

[font.normal]
family = "MonaspiceNe NF Medium"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[window.padding]
x = 10
y = 10
