complete -c translate -a "(
    echo ace_Arab
    echo ace_Latn
    echo acm_Arab
    echo acq_Arab
    echo aeb_Arab
    echo afr_Latn
    echo ajp_Arab
    echo aka_Latn
    echo amh_Ethi
    echo apc_Arab
    echo arb_Arab
    echo arb_Latn
    echo ars_Arab
    echo ary_Arab
    echo arz_Arab
    echo asm_Beng
    echo ast_Latn
    echo awa_Deva
    echo ayr_Latn
    echo azb_Arab
    echo azj_Latn
    echo bak_Cyrl
    echo bam_Latn
    echo ban_Latn
    echo bel_Cyrl
    echo bem_Latn
    echo ben_Beng
    echo bho_Deva
    echo bjn_Arab
    echo bjn_Latn
    echo bod_Tibt
    echo bos_Latn
    echo bug_Latn
    echo bul_Cyrl
    echo cat_Latn
    echo ceb_Latn
    echo ces_Latn
    echo cjk_Latn
    echo ckb_Arab
    echo crh_Latn
    echo cym_Latn
    echo dan_Latn
    echo deu_Latn
    echo dik_Latn
    echo dyu_Latn
    echo dzo_Tibt
    echo ell_Grek
    echo eng_Latn
    echo epo_Latn
    echo est_Latn
    echo eus_Latn
    echo ewe_Latn
    echo fao_Latn
    echo fij_Latn
    echo fin_Latn
    echo fon_Latn
    echo fra_Latn
    echo fur_Latn
    echo fuv_Latn
    echo gla_Latn
    echo gle_Latn
    echo glg_Latn
    echo grn_Latn
    echo guj_Gujr
    echo hat_Latn
    echo hau_Latn
    echo heb_Hebr
    echo hin_Deva
    echo hne_Deva
    echo hrv_Latn
    echo hun_Latn
    echo hye_Armn
    echo ibo_Latn
    echo ilo_Latn
    echo ind_Latn
    echo isl_Latn
    echo ita_Latn
    echo jav_Latn
    echo jpn_Jpan
    echo kab_Latn
    echo kac_Latn
    echo kam_Latn
    echo kan_Knda
    echo kas_Arab
    echo kas_Deva
    echo kat_Geor
    echo knc_Arab
    echo knc_Latn
    echo kaz_Cyrl
    echo kbp_Latn
    echo kea_Latn
    echo khm_Khmr
    echo kik_Latn
    echo kin_Latn
    echo kir_Cyrl
    echo kmb_Latn
    echo kmr_Latn
    echo kon_Latn
    echo kor_Hang
    echo lao_Laoo
    echo lij_Latn
    echo lim_Latn
    echo lin_Latn
    echo lit_Latn
    echo lmo_Latn
    echo ltg_Latn
    echo ltz_Latn
    echo lua_Latn
    echo lug_Latn
    echo luo_Latn
    echo lus_Latn
    echo lvs_Latn
    echo mag_Deva
    echo mai_Deva
    echo mal_Mlym
    echo mar_Deva
    echo min_Arab
    echo min_Latn
    echo mkd_Cyrl
    echo plt_Latn
    echo mlt_Latn
    echo mni_Beng
    echo khk_Cyrl
    echo mos_Latn
    echo mri_Latn
    echo mya_Mymr
    echo nld_Latn
    echo nno_Latn
    echo nob_Latn
    echo npi_Deva
    echo nso_Latn
    echo nus_Latn
    echo nya_Latn
    echo oci_Latn
    echo gaz_Latn
    echo ory_Orya
    echo pag_Latn
    echo pan_Guru
    echo pap_Latn
    echo pes_Arab
    echo pol_Latn
    echo por_Latn
    echo prs_Arab
    echo pbt_Arab
    echo quy_Latn
    echo ron_Latn
    echo run_Latn
    echo rus_Cyrl
    echo sag_Latn
    echo san_Deva
    echo sat_Olck
    echo scn_Latn
    echo shn_Mymr
    echo sin_Sinh
    echo slk_Latn
    echo slv_Latn
    echo smo_Latn
    echo sna_Latn
    echo snd_Arab
    echo som_Latn
    echo sot_Latn
    echo spa_Latn
    echo als_Latn
    echo srd_Latn
    echo srp_Cyrl
    echo ssw_Latn
    echo sun_Latn
    echo swe_Latn
    echo swh_Latn
    echo szl_Latn
    echo tam_Taml
    echo tat_Cyrl
    echo tel_Telu
    echo tgk_Cyrl
    echo tgl_Latn
    echo tha_Thai
    echo tir_Ethi
    echo taq_Latn
    echo taq_Tfng
    echo tpi_Latn
    echo tsn_Latn
    echo tso_Latn
    echo tuk_Latn
    echo tum_Latn
    echo tur_Latn
    echo twi_Latn
    echo tzm_Tfng
    echo uig_Arab
    echo ukr_Cyrl
    echo umb_Latn
    echo urd_Arab
    echo uzn_Latn
    echo vec_Latn
    echo vie_Latn
    echo war_Latn
    echo wol_Latn
    echo xho_Latn
    echo ydd_Hebr
    echo yor_Latn
    echo yue_Hant
    echo zho_Hans
    echo zho_Hant
    echo zsm_Latn
    echo zul_Latn
)"
