return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
            local parsers = {
                "ada",
                "agda",
                "angular",
                "apex",
                "arduino",
                "asm",
                "astro",
                "authzed",
                "awk",
                "bash",
                "bass",
                "beancount",
                "bibtex",
                "bicep",
                "bitbake",
                "blade",
                "c",
                "c_sharp",
                "cairo",
                "capnp",
                "chatito",
                "circom",
                "clojure",
                "cmake",
                "comment",
                "commonlisp",
                "cooklang",
                "corn",
                "cpon",
                "cpp",
                "css",
                "csv",
                "cuda",
                "cue",
                "cylc",
                "d",
                "dart",
                "devicetree",
                "dhall",
                "diff",
                "disassembly",
                "djot",
                "dockerfile",
                "dot",
                "doxygen",
                "dtd",
                "earthfile",
                "ebnf",
                "editorconfig",
                "eex",
                "elixir",
                "elm",
                "elsa",
                "elvish",
                "embedded_template",
                "erlang",
                "fennel",
                "fidl",
                "firrtl",
                "fish",
                "foam",
                "forth",
                "fortran",
                "fsh",
                "func",
                "gdscript",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "gleam",
                "glimmer",
                "glsl",
                "gnuplot",
                "go",
                "godot_resource",
                "gomod",
                "gosum",
                "gowork",
                "gpg",
                "graphql",
                "groovy",
                "gstlaunch",
                "hack",
                "hare",
                "haskell",
                "haskell_persistent",
                "hcl",
                "heex",
                "helm",
                "hjson",
                "hlsl",
                "hocon",
                "hoon",
                "html",
                "htmldjango",
                "http",
                "hurl",
                "hyprlang",
                "idl",
                "ini",
                "inko",
                "ispc",
                "janet_simple",
                "java",
                "javascript",
                "jq",
                "jsdoc",
                "json",
                "json5",
                "jsonnet",
                "julia",
                "just",
                "kconfig",
                "kdl",
                "kotlin",
                "kusto",
                "lalrpop",
                "latex",
                "ledger",
                "leo",
                "linkerscript",
                "liquid",
                "liquidsoap",
                "llvm",
                "lua",
                "luadoc",
                "luap",
                "luau",
                "m68k",
                "make",
                "markdown",
                "markdown_inline",
                "matlab",
                "mermaid",
                "meson",
                "mlir",
                "muttrc",
                "nasm",
                "nginx",
                "nickel",
                "nim",
                "nim_format_string",
                "ninja",
                "nix",
                "nqc",
                "objc",
                "objdump",
                "ocaml",
                "ocaml_interface",
                "ocamllex",
                "odin",
                "pascal",
                "passwd",
                "pem",
                "perl",
                "php",
                "php_only",
                "phpdoc",
                "pioasm",
                "po",
                "pod",
                "poe_filter",
                "pony",
                "printf",
                "prisma",
                "promql",
                "properties",
                "proto",
                "prql",
                "psv",
                "pug",
                "puppet",
                "purescript",
                "pymanifest",
                "python",
                "ql",
                "qmldir",
                "qmljs",
                "query",
                "r",
                "racket",
                "rasi",
                "rbs",
                "re2c",
                "readline",
                "regex",
                "rego",
                "requirements",
                "rnoweb",
                "robot",
                "roc",
                "ron",
                "rst",
                "ruby",
                "rust",
                "scala",
                "scheme",
                "scss",
                "slang",
                "slint",
                "smali",
                "smithy",
                "snakemake",
                "solidity",
                "soql",
                "sosl",
                "sparql",
                "sql",
                "squirrel",
                "ssh_config",
                "starlark",
                "strace",
                "styled",
                "supercollider",
                "surface",
                "svelte",
                "swift",
                "sxhkdrc",
                "systemtap",
                "t32",
                "tablegen",
                "tact",
                "tcl",
                "teal",
                "templ",
                "terraform",
                "textproto",
                "thrift",
                "tiger",
                "tlaplus",
                "tmux",
                "todotxt",
                "toml",
                "tsv",
                "tsx",
                "turtle",
                "twig",
                "typescript",
                "typespec",
                "typoscript",
                "typst",
                "udev",
                "ungrammar",
                "unison",
                "usd",
                "uxntal",
                "v",
                "vala",
                "vento",
                "vhdl",
                "vhs",
                "vim",
                "vimdoc",
                "vue",
                "wgsl",
                "wgsl_bevy",
                "wing",
                "wit",
                "xcompose",
                "xml",
                "yaml",
                "yang",
                "yuck",
                "zig",
            }

            local treesitter = require("nvim-treesitter")
            treesitter.setup()
            treesitter.install(parsers)

            vim.api.nvim_create_autocmd("FileType", {
                callback = function(args)
                    if vim.list_contains(treesitter.get_installed(), vim.treesitter.language.get_lang(args.match)) then
                        vim.treesitter.start(args.buf)
                    end
                end,
            })
        end,
   },
   {
        "nvim-treesitter/nvim-treesitter-textobjects",
        config = function()
            require("nvim-treesitter-textobjects").setup({
                select = {
                    lookahead = true,
                    include_surrounding_whitespace = true,
                    selection_modes = {
                        ["@function.outer"] = "v",
                        ["@function.inner"] = "V",
                        ["@class.outer"] = "V",
                    },
                },
                move = {
                    set_jumps = true,
                },
            })

            local move = require("nvim-treesitter-textobjects.move")

            local goto_next_start = function()
                move.goto_next_start("@function.outer", "textobjects")
                vim.cmd("normal! zz")
            end

            local goto_previous_start = function()
                move.goto_previous_start("@function.outer", "textobjects")
                vim.cmd("normal! zz")
            end

            vim.keymap.set({"n", "x", "o"}, "]]", goto_next_start)
            vim.keymap.set({"n", "x", "o"}, "[[", goto_previous_start)
        end
   }
}
